### ISSUE TITLE
Temperature never stops increasing/decreasing when temp offset is set 

### ISSUE THREAD

**Issue by Olaruci** [melkati/CO2-Gadget#155]
**CO2 Gadget version and flavour**
->[STUP] CO2 Gadget Version: 0.9.001 Flavour: TTGO T-Display
-->[STUP] Version compiled: Jan 30 2024 at 10:59:54

**CO2 Gadget installation method?**
- Easy Web flasher

**Describe the bug**
When a temperature offset is set the displayed temperature never stops incrementing the offset.
So with an offset of -10 it displayed -182 degC and keeps decreasing.

**To Reproduce**
Put any offset from the display menu and it will happen.

**Expected behavior**
Normal offset behavior.

**Screenshots**
![20240129_221026](https://github.com/melkati/CO2-Gadget/assets/47052441/590cedb3-8cd0-4ebc-abff-1376eca17530)

![20240129_221504](https://github.com/melkati/CO2-Gadget/assets/47052441/d21187ea-23c0-48d8-934d-3a1ca9c0eb40)

**Comment by melkati** [comment]
Hi. Thanks for reporting this.

What temperature sensor are you using?

**Comment by melkati** [comment]
Sensirion sensors calculate offset internally (in their own built-in firmware), CO2 Gadget just pass the offset value to the sensor.

The bug is that the offset must always be a positive number (it will drop temperature by this number and also will recalculate relative humidity).

I'll update the menu to only accept positive numbers.

While I do the modifications, please just change the "-10" temperature offset value to "10").

Note: Be prepared when you set an offset to not see the change immediately. Sensirion's firmware takes a while to adjust it (up to some minutes).

Thank you for reporting it. 😀

**Comment by Olaruci** [comment]
![20240203_154944](https://github.com/melkati/CO2-Gadget/assets/47052441/eb311a73-4029-48f6-b333-27b703641aa9)
With positive offset it seems like nothing happens. I've let it 24h...

**Comment by melkati** [comment]
Thanks for reporting it, I have been able to replicate it and it seems that there are still some errors.

I'm going to look at it in depth because at first glance I can't see anything wrong.

**Comment by melkati** [comment]
I think it's fixed now. I tested it and it's working fine on my end.

As the fix is not included in the release version, I compiled a beta version just for you so you can check if it's working fine and report before I insert the modifications in the general release version.

Please, install it from here (be sure to choose the one stated as "CO2 Gadget Beta-Development Version"):
https://emariete.com/en/co2-meter-gadget/#CO2_Gadget_Version_Beta-Desarrollo

After flashing, please make sure it's running the right version: CO2 Gadget Version: 0.9.010 Flavour: TTGO T-Display Sandwich

Thank you! :-)

**Comment by Olaruci** [comment]
Hi , I don't have the Sandwich vesion, the regular TTGO T-Display

**Comment by melkati** [comment]
> Hi, I don't have the Sandwich version, the regular TTGO T-Display

Opps! I'm very sorry, I oversaw that.

I just compiled a new version for you.

Please, install it from here (be sure to choose the one stated as "CO2 Gadget Beta-Development Version"):
https://emariete.com/en/co2-meter-gadget/#CO2_Gadget_Version_Beta-Desarrollo

After flashing, please make sure it's running the right version: CO2 Gadget Version: 0.9.014 Flavour: TTGO T-Display

Thank you! 😇

**Comment by Olaruci** [comment]
Thanks. 
Yes now the offset is working. And is limited to be positive 0-30.

On information page didn't show 9.014 but is for sure the beta you provided.![20240204_224929.jpg](https://github.com/melkati/CO2-Gadget/assets/47052441/8caab9ca-cd35-4078-b37c-32748072646b)

![20240204_224849.jpg](https://github.com/melkati/CO2-Gadget/assets/47052441/389792f2-7936-4c36-b4a0-e47331ebd2ef)

**Comment by melkati** [comment]
Great! Thank you.

The fix will be included in the next release in the next few days (we are finishing some more fixes and improvements).
